"""Add gambling_sessions table

Revision ID: 3e5106c90db5
Revises: 49223842cd91
Create Date: 2025-12-24 10:48:50.649100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5106c90db5'
down_revision: Union[str, None] = '49223842cd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambling_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('buy_in', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_out', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_result', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gambling_sessions')
    # ### end Alembic commands ###
