"""Initial budget system

Revision ID: ffc95f18015d
Revises: 
Create Date: 2025-12-26 10:00:25.044495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc95f18015d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spending_insights')
    op.drop_table('merchant_category_mappings')
    op.drop_column('budget_categories', 'color')
    op.drop_column('budget_categories', 'icon')
    op.add_column('budgets', sa.Column('period_type', sa.String(), nullable=False))
    op.add_column('budgets', sa.Column('has_monthly_obligations', sa.Boolean(), nullable=True))
    op.add_column('budgets', sa.Column('period_start_date', sa.DateTime(), nullable=False))
    op.add_column('budgets', sa.Column('next_period_date', sa.DateTime(), nullable=False))
    op.add_column('budgets', sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('budgets', 'observation_end_date')
    op.drop_column('budgets', 'average_monthly_income')
    op.drop_column('budgets', 'observation_start_date')
    op.drop_column('budgets', 'budget_cadence')
    op.drop_column('budgets', 'category_budgets')
    op.drop_column('budgets', 'next_expected_paycheck')
    op.drop_column('budgets', 'last_paycheck_date')
    op.drop_column('budgets', 'income_frequency')
    op.drop_column('budgets', 'created_from_insights')
    op.drop_column('budgets', 'last_paycheck_amount')
    op.add_column('transactions', sa.Column('budget_period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'budget_period')
    op.add_column('budgets', sa.Column('last_paycheck_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('created_from_insights', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('income_frequency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('last_paycheck_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('next_expected_paycheck', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('category_budgets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('budget_cadence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('observation_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('budgets', sa.Column('average_monthly_income', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('observation_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('budgets', 'total_income')
    op.drop_column('budgets', 'next_period_date')
    op.drop_column('budgets', 'period_start_date')
    op.drop_column('budgets', 'has_monthly_obligations')
    op.drop_column('budgets', 'period_type')
    op.add_column('budget_categories', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budget_categories', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('merchant_category_mappings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('merchant_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bucket', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assignment_count', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='merchant_category_mappings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='merchant_category_mappings_pkey')
    )
    op.create_table('spending_insights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('week_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_income', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_spending', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('category_spending', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recurring_expenses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='spending_insights_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='spending_insights_pkey')
    )
    # ### end Alembic commands ###
